format = """
[█](cyan)\
$os\
$username\
[🬶𜵟𜴻𜴃](bg:red fg:cyan)\
$directory\
[◤](fg:red bg:orange)\
$git_branch\
$git_status\
[◤](fg:orange bg:yellow)\
$c\
$cpp\
$elixir\
$elm\
$golang\
$haskell\
$python\
$java\
$kotlin\
$gradle\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[◤](fg:yellow bg:pink)\
$docker_context\
[◤](fg:pink bg:blue)\
$time\
[ ](fg:blue)\
"""

palette = 'foreverblush'
# Disable the blank line at the start of the prompt
# add_newline = false
"$schema" = 'https://starship.rs/config-schema.json'
# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:light-white bg:cyan"
style_root = "fg:light-white bg:cyan"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:cyan"
disabled = true # Disabled by default

[directory]
style = "fg:light-white bg:red"
read_only = " 󰌾"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "
[c]
symbol = " "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[cmake]
symbol = " "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:green"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:orange"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:orange"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[kotlin]
symbol = " "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = " "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[meson]
symbol = "󰔷 "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[perl]
symbol = " "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = " "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:yellow"
format = '[ $symbol( $version)(\(#$virtualenv\)) ]($style)'

[rust]
symbol = ""
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[ruby]
symbol = " "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[zig]
symbol = " "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[package]
symbol = "󰏗 "

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:light-white bg:blue"
format = '[ ♥ $time ]($style)'

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:pink)'
vimcmd_replace_symbol = '[❮](bold fg:pink)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[palettes.foreverblush]
#: black
black = "#232d2b"
light-black = "#37413f"
red = "#f18095"
green = "#9be980"
yellow = "#fad69d"
orange = "#fc9d6f"
blue = "#afbeed"
pink = "#eea1A9"
lilac = "#bfa1ee"
cyan = "#93e4aa"
white = "#a9b9ac"
light-white = "#fbf5f9"
