if-shell 'which fish' 'set -g default-command fish'

# unbind C-b
# set-option -g prefix C-a
# bind-key C-a send-prefix

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.config/tmux/tmux.conf

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'ofirgall/tmux-window-name'
set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'brendandebeasi/tabby'
set -g @plugin 'noscript/tmux-mighty-scroll'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @plugin 'whame/tmux-modal'
set -g @plugin 'tmux-plugins/tmux-yank'

set-option -g mouse on

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
