[font]
size = 11.0
builtin_box_drawing = true

[font.bold]
family = "Maple Mono NF CN"
style = "Bold"

[font.bold_italic]
family = "Maple Mono NF CN"
style = "Bold Oblique"

[font.italic]
family = "Maple Mono NF CN"
style = "Oblique"

[font.normal]
family = "Maple Mono NF CN"
style = "Regular"
