#!/usr/bin/sh

# Set background and border color
riverctl xcursor-theme 'Bibata' 24
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75
riverctl spawn "swaybg -m fit -i $HOME/picurte/wallpapers/386348-sumi_0525.png"
